engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
    - js_source/
    - index.html
exclude_paths:
- js/phaser.js
- js/game.js